### ISSUE TITLE
Wait till workflow is complete option

### ISSUE THREAD

**Issue by achristofferson-bbi** [nf-core/tower-action#13]
Is it possible for the nf-core/tower-action on github to wait for successful completion of a run instead of flagging it as successful as soon as it's submitted?

**Comment by ewels** [comment]
It wasn't (I asked for it - https://github.com/seqeralabs/tower-cli/issues/177 and it was already planned in https://github.com/seqeralabs/tower-cli/issues/12), but it is now - recently released in tw-cli version 0.6.

It's on my to-do list to update this action to make use of this ASAP 👍🏻 Any thoughts about implementation? I'm thinking that most people will want it, so I should make it use `--wait` by default..

**Comment by achristofferson-bbi** [comment]
Sounds good to me. For those that don't want it to wait, how would they turn it off? Additional "with" variable in their workflow.yml?

**Comment by ewels** [comment]
Yup 👍🏻 Something like:

```yaml
with:
    wait: false
```

`wait` would then normally take a string for the desired state which could be customised, but would default to `SUCCEEDED` if not set.

**Comment by achristofferson-bbi** [comment]
👍 This is going to be awesome! Thanks so much for updating this.

**Comment by ewels** [comment]
Should be closed imminently in https://github.com/seqeralabs/action-tower-launch/pull/1

Closing this issue a little early as I'm moving the repo and want to archive it. Should be implemented in the new repo v. soon though. We can continue discussion there in a new issue if needed.

Thanks for the issue!
